#!/bin/bash
# TODO Add custom autocomplete menu
if [ -z "$1" ]; then
	echo "usage: $0 [project_new] [project_config]"
	exit
fi
if [ "$1" = "project_new" ]; then
	# No project name supplied
	if [ -z "$2" ]; then
		echo usage: $0 project_new ProjectName
		exit
	fi
	# Folder exists
	if [ -d "$2" ]; then
		echo Project $2 already exists. Use: $0 project_config ProjectName src_path bin_path
		exit
	fi
	# Create folder structure
	mkdir $2 $2/bin $2/src
	# Create config file and fill with created paths
	touch $2/vji.conf
	java Config write $(pwd)/$2/vji.conf $(pwd)/$2/src $(pwd)/$2/bin
fi
if [ "$1" = "project_config" ]; then
	# Need all arguments
	if [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ] ; then
		echo "Not enough arguments supplied."
		echo "usage: $0 config ProjectName src_path bin_path"
		# TODO Update Config.java to accept relative paths
		echo "(src_path and bin_path must be absolute for now)"
		exit
	fi
	# Project does not exist
	if [ ! -d "$2" ]; then
		echo "[Warning] Project does not exist. Use: $0 project_new ProjectName."
		exit
	fi
	# Project exists but doesn't have bin or src folders
	if [ ! -d "$2/src" ]; then
		echo "[Warning] Project does not yet have a src folder. It will be created."
		mkdir $2/src
	fi
	if [ ! -d "$2/bin" ]; then
		echo "[Warning] Project does not yet have a bin folder. It will be created."
		mkdir $2/bin
	fi
	# Show a warning when the config file does not exist
	if [ ! -f "$2/vji.conf" ]; then
		echo "[Warning] Config file does not exist yet. It will be created."
	fi
	# Update config file 
	java Config write $(pwd)/$2/vji.conf $3 $4
fi
